alias vi="nvim"
alias vim="vi"
alias ls="ls --color"

# Bazel
function bzlw {
  echo "Getting all workflows for $1"
  bzl query "kind(_cnab_workflow_wrapper, $1)"
}

function bzlt {
  echo "Getting all targets for $1"
  bzl query "kind(cnab_action_invocation, $1)"
}

# K8s
alias k="kubectl"

# Workspace
export WORKSPACE="$(echo $USER | sed s/\\.//g)"

function workspace {
  pkill workspaces; (workspaces proxy $WORKSPACE > /dev/null 2>&1 &) && kitty +kitten ssh workspace-$WORKSPACE
}

# Kitty ssh
alias s="kitty +kitten ssh"
